/**
 * Script to populate UUID and EdVerse ID for existing users
 *
 * This script:
 * 1. Generates UUID for all users who don't have one
 * 2. Generates EdVerse ID for all users based on their role
 *
 * Run with: npx ts-node src/scripts/populate-uuid-edverse-id.ts
 */

import { PrismaClient } from '@prisma/client'
import { generateEdVerseId } from '../utils/edverse-id.util'

const prisma = new PrismaClient()

async function main() {
  console.log('🚀 Starting UUID and EdVerse ID population...\n')

  try {
    // Get all users
    const users = await prisma.user.findMany({
      include: {
        role: true,
      },
      orderBy: {
        id: 'asc',
      },
    })

    console.log(`📊 Found ${users.length} users to process\n`)

    // Track sequences per role/year
    const sequenceCounters: Record<string, number> = {}

    let updatedCount = 0

    for (const user of users) {
      const roleName = user.role.roleName.toLowerCase()
      const year = new Date(user.createdAt).getFullYear()
      const key = `${roleName}-${year}`

      // Initialize or increment sequence for this role/year
      if (!sequenceCounters[key]) {
        sequenceCounters[key] = 1
      } else {
        sequenceCounters[key]++
      }

      const sequence = sequenceCounters[key]

      // Generate EdVerse ID if not exists
      let edverseId = user.edverseId
      if (!edverseId) {
        edverseId = generateEdVerseId(roleName, sequence, year)
      }

      // Update user with UUID (auto-generated by Prisma) and EdVerse ID
      await prisma.user.update({
        where: { id: user.id },
        data: {
          edverseId,
        },
      })

      updatedCount++
      console.log(`✅ Updated user ${user.id}: ${user.name} -> ${edverseId}`)
    }

    console.log(`\n✨ Successfully updated ${updatedCount} users!`)
    console.log('\n📋 Summary:')
    Object.entries(sequenceCounters).forEach(([key, count]) => {
      console.log(`   ${key}: ${count} users`)
    })
  } catch (error) {
    console.error('❌ Error:', error)
    throw error
  } finally {
    await prisma.$disconnect()
  }
}

main().catch(error => {
  console.error(error)
  process.exit(1)
})
