import { Prisma } from '.prisma/client'
import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common'
import * as bcrypt from 'bcryptjs'
import { CreateParentDataDto } from '../common/dto/user.dto'
import { IdGenerationService } from '../id-generation/id-generation.service'
import { PrismaService } from '../prisma/prisma.service'
import { generateTemporaryPassword } from '../utils/kramid.util'
import { CreateUserDto, UpdateUserDto, UserQueryDto } from './dto/user.dto'

@Injectable()
export class UsersService {
  constructor(
    private prisma: PrismaService,
    private idGenerationService: IdGenerationService
  ) {}

  private getFullName(firstName: string, lastName: string): string {
    return `${firstName} ${lastName}`.trim()
  }

  async create(createUserDto: CreateUserDto) {
    // Check if email already exists
    const existingUser = await this.prisma.user.findUnique({
      where: { email: createUserDto.email },
    })

    if (existingUser) {
      throw new ConflictException('User with this email already exists')
    }

    // Check if phone number already exists (if provided)
    if (createUserDto.phoneNumber) {
      const existingPhoneUser = await this.prisma.user.findFirst({
        where: { phone: createUserDto.phoneNumber },
      })

      if (existingPhoneUser) {
        throw new ConflictException(
          'User with this phone number already exists'
        )
      }
    }

    // Get role to determine what profile to create
    const role = await this.prisma.role.findUnique({
      where: { id: createUserDto.roleId },
    })

    if (!role) {
      throw new NotFoundException('Role not found')
    }

    // Get institution for Kram ID generation
    const institution = await this.prisma.institution.findUnique({
      where: { id: createUserDto.institutionId },
      select: { id: true, code: true },
    })

    if (!institution) {
      throw new NotFoundException('Institution not found')
    }

    if (!institution.code) {
      throw new BadRequestException(
        'Institution code not configured. Please contact administrator.'
      )
    }

    // Validate role-specific data is provided
    this.validateRoleSpecificData(role.roleName, createUserDto)

    // Note: Kram ID is auto-generated by database trigger
    // No need to manually generate it here

    // Generate temporary password if not provided
    const finalPassword =
      createUserDto.password ||
      generateTemporaryPassword(createUserDto.firstName, createUserDto.lastName)
    const hashedPassword = await bcrypt.hash(finalPassword, 12)
    const isTemporaryPassword = !createUserDto.password

    // Create user and role-specific profile in a transaction
    const result = await this.prisma.$transaction(async tx => {
      // Create base user
      const user = await tx.user.create({
        data: {
          roleId: createUserDto.roleId,
          email: createUserDto.email,
          passwordHash: hashedPassword,
          phone: createUserDto.phoneNumber,
          firstName: createUserDto.firstName,
          lastName: createUserDto.lastName,
          accountStatus: isTemporaryPassword
            ? 'INACTIVE'
            : createUserDto.accountStatus || 'ACTIVE',
        },
      })

      // Create role-specific profile
      let profile: unknown = null

      switch (role.roleName) {
        case 'student':
          if (createUserDto.studentData || role.roleName === 'student') {
            const studentData = createUserDto.studentData || {}

            // Get course code for ID generation
            let courseCode = 'GEN'
            if (studentData.courseId) {
              const course = await tx.course.findUnique({
                where: { id: studentData.courseId },
                select: { code: true },
              })
              if (course?.code) {
                courseCode = course.code
              }
            }

            // Generate IDs using IdGenerationService (outside transaction for atomic sequences)
            const admissionNumber =
              await this.idGenerationService.generateAdmissionNumber({
                institutionId: createUserDto.institutionId,
                courseCode,
                section: studentData.section,
                customValue: studentData.admissionNumber,
              })

            const rollNumber =
              await this.idGenerationService.generateRollNumber({
                institutionId: createUserDto.institutionId,
                courseCode,
                section: studentData.section,
                customValue: studentData.rollNumber,
              })

            profile = await tx.student.create({
              data: {
                userId: user.id,
                institutionId: createUserDto.institutionId,
                courseId: studentData.courseId,
                admissionNumber,
                rollNumber,
                admissionDate: studentData.admissionDate
                  ? new Date(studentData.admissionDate)
                  : null,
                currentSemester: studentData.currentSemester,
                currentYear: studentData.currentYear,
                section: studentData.section,
                studentType: studentData.studentType || 'REGULAR',
                residentialStatus:
                  studentData.residentialStatus || 'DAY_SCHOLAR',
                transportRequired: studentData.transportRequired || false,
                bloodGroup: studentData.bloodGroup,
                medicalConditions: studentData.medicalConditions,
              },
            })

            // Create parent records if student data includes parent information
            if (
              studentData.fatherInfo ||
              studentData.motherInfo ||
              studentData.guardianInfo
            ) {
              await this.createParentRecords(
                (profile as { id: number }).id,
                studentData,
                createUserDto.institutionId
              )
            }
          }
          break

        case 'teacher':
          if (createUserDto.teacherData || role.roleName === 'teacher') {
            const teacherData = createUserDto.teacherData || {}

            // Generate employee ID using IdGenerationService
            const employeeId =
              await this.idGenerationService.generateTeacherEmployeeId({
                institutionId: createUserDto.institutionId,
                customValue: teacherData.employeeId,
              })

            profile = await tx.teacher.create({
              data: {
                userId: user.id,
                institutionId: createUserDto.institutionId,
                employeeId,
                designation: teacherData.designation,
                specialization: teacherData.specialization,
                qualification: teacherData.qualification,
                experienceYears: teacherData.experienceYears,
                joinDate: teacherData.joinDate
                  ? new Date(teacherData.joinDate)
                  : null,
                salary: teacherData.salary,
                employmentType: teacherData.employmentType || 'FULL_TIME',
                officeLocation: teacherData.officeLocation,
                officeHours: teacherData.officeHours,
                researchInterests: teacherData.researchInterests,
                publications: teacherData.publications,
              },
            })
          }
          break

        case 'staff':
          if (createUserDto.staffData || role.roleName === 'staff') {
            const staffData = createUserDto.staffData || {
              staffType: 'ADMINISTRATIVE' as const,
              designation: 'Staff Member',
            }

            // Generate employee ID using IdGenerationService
            const employeeId =
              await this.idGenerationService.generateStaffEmployeeId({
                institutionId: createUserDto.institutionId,
                customValue: staffData.employeeId,
              })

            profile = await tx.staff.create({
              data: {
                userId: user.id,
                institutionId: createUserDto.institutionId,
                employeeId,
                staffType: staffData.staffType,
                designation: staffData.designation,
                department: staffData.department,
                joinDate: staffData.joinDate
                  ? new Date(staffData.joinDate)
                  : null,
                salary: staffData.salary,
                employmentType: staffData.employmentType || 'FULL_TIME',
                workingHours: staffData.workingHours,
                qualifications: staffData.qualifications,
                experience: staffData.experience,
                emergencyContact: staffData.emergencyContact,
                address: staffData.address,
              },
            })
          }
          break

        case 'parent':
          if (createUserDto.parentData || role.roleName === 'parent') {
            const parentData: Partial<CreateParentDataDto> =
              createUserDto.parentData || {}

            if (
              !parentData.childKramid ||
              parentData.childKramid.trim() === ''
            ) {
              throw new BadRequestException(
                'parentData with valid childKramid is required for parent role'
              )
            }

            // Find the child student by Kram ID
            const childUser = await tx.user.findUnique({
              where: { kramid: parentData.childKramid.trim() },
              include: { student: true },
            })

            if (!childUser || !childUser.student) {
              throw new NotFoundException(
                `Student not found with Kram ID: ${parentData.childKramid}`
              )
            }

            profile = await tx.parent.create({
              data: {
                userId: user.id,
                studentId: childUser.student.id,
                relation:
                  (parentData.relation as
                    | 'FATHER'
                    | 'MOTHER'
                    | 'GUARDIAN'
                    | 'OTHER') || 'GUARDIAN',
                isPrimaryContact: parentData.isPrimaryContact ?? true,
                occupation: parentData.occupation,
                annualIncome: parentData.annualIncome,
                educationLevel: parentData.educationLevel,
              },
            })
          }
          break

        // Admin and super_admin don't need additional profiles
        case 'admin':
        case 'super_admin':
          // No additional profile needed
          break

        default:
          // For any other roles, no additional profile
          break
      }

      return {
        user,
        profile,
        generatedPassword: isTemporaryPassword ? finalPassword : null,
      }
    })

    // Fetch complete user with all relations
    const completeUser = await this.prisma.user.findUnique({
      where: { id: result.user.id },
      include: {
        role: true,
        student: {
          include: {
            institution: { select: { id: true, name: true, type: true } },
            course: { select: { id: true, name: true, code: true } },
          },
        },
        teacher: {
          include: {
            institution: { select: { id: true, name: true, type: true } },
          },
        },
        parent: {
          include: {
            student: {
              include: {
                user: {
                  select: {
                    id: true,
                    firstName: true,
                    lastName: true,
                    email: true,
                    kramid: true,
                  },
                },
              },
            },
          },
        },
        staff: {
          include: {
            institution: { select: { id: true, name: true, type: true } },
          },
        },
      },
    })

    // Remove passwordHash from response
    if (completeUser) {
      delete completeUser.passwordHash
    }

    return {
      success: true,
      message: 'User created successfully',
      data: completeUser,
      ...(result.generatedPassword && {
        temporaryPassword: result.generatedPassword,
        note: 'User must change password on first login',
      }),
    }
  }

  private validateRoleSpecificData(
    roleName: string,
    createUserDto: CreateUserDto
  ) {
    switch (roleName) {
      case 'student':
        // studentData is optional - admissionNumber/rollNumber auto-generated
        break

      case 'teacher':
        // teacherData is optional - employeeId auto-generated
        break

      case 'staff':
        if (
          !createUserDto.staffData?.staffType ||
          !createUserDto.staffData?.designation
        ) {
          throw new BadRequestException(
            'staffData with staffType and designation is required for staff role'
          )
        }
        break

      case 'parent':
        if (!createUserDto.parentData?.childKramid) {
          throw new BadRequestException(
            'parentData with childKramid is required for parent role'
          )
        }
        break

      // admin, super_admin don't require additional data
    }
  }

  async findAll(query: UserQueryDto, institutionId: number | null = null) {
    const { page, limit, search, roleId, accountStatus, sortBy, sortOrder } =
      query
    const skip = (page - 1) * limit

    // Build where clause with proper Prisma typing
    const where: Prisma.UserWhereInput = {
      ...(search && {
        OR: [
          { firstName: { contains: search, mode: 'insensitive' } },
          { lastName: { contains: search, mode: 'insensitive' } },
          { email: { contains: search, mode: 'insensitive' } },
          { phone: { contains: search, mode: 'insensitive' } },
        ],
      }),
      ...(roleId && { roleId }),
      ...(accountStatus && { accountStatus }),
    }

    if (institutionId) {
      where.AND = [
        ...(Array.isArray(where.AND) ? where.AND : []),
        {
          OR: [
            { institutionId },
            { student: { institutionId } },
            { teacher: { institutionId } },
            { staff: { institutionId } },
            { parent: { student: { institutionId } } },
          ],
        },
      ]
    }

    // Build orderBy clause with proper typing
    const orderBy: Prisma.UserOrderByWithRelationInput = {
      [sortBy]: sortOrder,
    }

    // Get users with pagination
    const [users, total] = await Promise.all([
      this.prisma.user.findMany({
        where,
        skip,
        take: limit,
        orderBy,
        include: {
          role: true,
          student: true,
          teacher: true,
          parent: true,
          staff: true,
        },
      }),
      this.prisma.user.count({ where }),
    ])

    // Remove passwordHash from response
    const usersWithoutPasswords = users.map(user => {
      delete user.passwordHash
      return user
    })

    return {
      data: usersWithoutPasswords,
      pagination: {
        page,
        limit,
        total,
        pages: Math.ceil(total / limit),
      },
    }
  }

  async findOne(id: number) {
    const user = await this.prisma.user.findUnique({
      where: { id },
      include: {
        role: true,
        student: {
          include: {
            institution: true,
            course: true,
            parents: {
              include: {
                user: true,
              },
            },
          },
        },
        teacher: {
          include: {
            institution: true,
          },
        },
        parent: {
          include: {
            student: {
              include: {
                user: true,
                institution: true,
                course: true,
              },
            },
          },
        },
        staff: {
          include: {
            institution: true,
          },
        },
      },
    })

    if (!user) {
      throw new NotFoundException(`User with ID ${id} not found`)
    }

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async findByEmail(email: string) {
    const user = await this.prisma.user.findUnique({
      where: { email },
      include: {
        role: true,
        student: true,
        teacher: true,
        parent: true,
        staff: true,
      },
    })

    if (!user) {
      throw new NotFoundException(`User with email ${email} not found`)
    }

    return user
  }

  async update(id: number, updateUserDto: UpdateUserDto) {
    // Check if user exists
    const existingUser = await this.prisma.user.findUnique({
      where: { id },
    })

    if (!existingUser) {
      throw new NotFoundException(`User with ID ${id} not found`)
    }

    // Check if email already exists (if being updated)
    if (
      updateUserDto.email &&
      updateUserDto.email.toLowerCase() !== existingUser.email?.toLowerCase()
    ) {
      const emailExists = await this.prisma.user.findUnique({
        where: { email: updateUserDto.email.toLowerCase() },
      })

      if (emailExists) {
        throw new ConflictException('User with this email already exists')
      }
    }

    // Check if phone number already exists (if being updated)
    if (
      updateUserDto.phoneNumber &&
      updateUserDto.phoneNumber !== existingUser.phone
    ) {
      const phoneExists = await this.prisma.user.findFirst({
        where: { phone: updateUserDto.phoneNumber },
      })

      if (phoneExists) {
        throw new ConflictException(
          'User with this phone number already exists'
        )
      }
    }

    // Build update data with proper typing
    const updateData: Prisma.UserUpdateInput = {
      ...(updateUserDto.roleId && { roleId: updateUserDto.roleId }),
      ...(updateUserDto.email && { email: updateUserDto.email.toLowerCase() }),
      ...(updateUserDto.phoneNumber && { phone: updateUserDto.phoneNumber }),
      // Handle firstName and lastName updates
      ...(updateUserDto.firstName && { firstName: updateUserDto.firstName }),
      ...(updateUserDto.lastName && { lastName: updateUserDto.lastName }),
      // Update the combined name field for backward compatibility
      ...(updateUserDto.firstName || updateUserDto.lastName
        ? {
            name: (() => {
              const firstName =
                updateUserDto.firstName || existingUser.firstName || ''
              const lastName =
                updateUserDto.lastName || existingUser.lastName || ''
              return `${firstName} ${lastName}`.trim()
            })(),
          }
        : {}),
      ...(updateUserDto.accountStatus && {
        accountStatus: updateUserDto.accountStatus,
      }),
    }

    // Hash password if being updated
    if (updateUserDto.password) {
      updateData.passwordHash = await bcrypt.hash(updateUserDto.password, 12)
    }

    // Update user
    const user = await this.prisma.user.update({
      where: { id },
      data: updateData,
      include: {
        role: true,
        student: true,
        teacher: true,
        parent: true,
        staff: true,
      },
    })

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async remove(id: number) {
    // Check if user exists
    const existingUser = await this.prisma.user.findUnique({
      where: { id },
    })

    if (!existingUser) {
      throw new NotFoundException(`User with ID ${id} not found`)
    }

    // Soft delete by updating status
    const user = await this.prisma.user.update({
      where: { id },
      data: { accountStatus: 'INACTIVE' },
      include: {
        role: true,
      },
    })

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async hardDelete(id: number) {
    // Check if user exists
    const existingUser = await this.prisma.user.findUnique({
      where: { id },
    })

    if (!existingUser) {
      throw new NotFoundException(`User with ID ${id} not found`)
    }

    // Hard delete user
    await this.prisma.user.delete({
      where: { id },
    })

    return { message: 'User deleted successfully' }
  }

  async getUsersByRole(
    roleId: number,
    query: UserQueryDto,
    institutionId: number | null = null
  ) {
    const { page, limit, search, accountStatus, sortBy, sortOrder } = query
    const skip = (page - 1) * limit

    // Build where clause with proper Prisma typing
    const where: Prisma.UserWhereInput = {
      roleId,
      ...(search && {
        OR: [
          { firstName: { contains: search, mode: 'insensitive' } },
          { lastName: { contains: search, mode: 'insensitive' } },
          { email: { contains: search, mode: 'insensitive' } },
          { phone: { contains: search, mode: 'insensitive' } },
        ],
      }),
      ...(accountStatus && { accountStatus }),
    }

    if (institutionId) {
      where.AND = [
        ...(Array.isArray(where.AND) ? where.AND : []),
        {
          OR: [
            { institutionId },
            { student: { institutionId } },
            { teacher: { institutionId } },
            { staff: { institutionId } },
            { parent: { student: { institutionId } } },
          ],
        },
      ]
    }

    // Build orderBy clause with proper typing
    const orderBy: Prisma.UserOrderByWithRelationInput = {
      [sortBy]: sortOrder,
    }

    // Get users with pagination
    const [users, total] = await Promise.all([
      this.prisma.user.findMany({
        where,
        skip,
        take: limit,
        orderBy,
        include: {
          role: true,
          student: true,
          teacher: true,
          parent: true,
          staff: true,
        },
      }),
      this.prisma.user.count({ where }),
    ])

    // Remove passwordHash from response
    const usersWithoutPasswords = users.map(user => {
      delete user.passwordHash
      return user
    })

    return {
      data: usersWithoutPasswords,
      pagination: {
        page,
        limit,
        total,
        pages: Math.ceil(total / limit),
      },
    }
  }

  async getUsersStats(institutionId: number | null = null) {
    const instWhere: Prisma.UserWhereInput | undefined = institutionId
      ? {
          OR: [
            { institutionId },
            { student: { institutionId } },
            { teacher: { institutionId } },
            { staff: { institutionId } },
            { parent: { student: { institutionId } } },
          ],
        }
      : undefined

    const baseWhere = instWhere ?? {}
    const [totalUsers, activeUsers, inactiveUsers, usersByRole] =
      await Promise.all([
        this.prisma.user.count({ where: baseWhere }),
        this.prisma.user.count({
          where: { ...baseWhere, accountStatus: 'ACTIVE' },
        }),
        this.prisma.user.count({
          where: { ...baseWhere, accountStatus: 'INACTIVE' },
        }),
        this.prisma.user.groupBy({
          by: ['roleId'],
          _count: { id: true },
          ...(instWhere && { where: instWhere }),
        }),
      ])

    // Get role names separately
    const roleIds = usersByRole.map(item => item.roleId)
    const roles = await this.prisma.role.findMany({
      where: { id: { in: roleIds } },
      select: { id: true, roleName: true },
    })

    const roleMap = new Map(roles.map(role => [role.id, role.roleName]))

    return {
      totalUsers,
      activeUsers,
      inactiveUsers,
      suspendedUsers: totalUsers - activeUsers - inactiveUsers,
      usersByRole: usersByRole.map(({ roleId, _count }) => ({
        roleId,
        count: _count.id,
        roleName: roleMap.get(roleId) || 'Unknown',
      })),
    }
  }

  // UUID-based methods
  async findByUuid(uuid: string, adminInstitutionId: number | null = null) {
    const user = await this.prisma.user.findUnique({
      where: { uuid },
      include: {
        role: true,
        student: {
          include: {
            institution: true,
            course: true,
            parents: {
              include: {
                user: true,
              },
            },
          },
        },
        teacher: {
          include: {
            institution: true,
          },
        },
        parent: {
          include: {
            student: {
              include: {
                user: true,
                institution: true,
                course: true,
              },
            },
          },
        },
        staff: {
          include: {
            institution: true,
          },
        },
      },
    })

    if (!user) {
      throw new NotFoundException(`User with UUID ${uuid} not found`)
    }

    const userInstitutionId =
      user.institutionId ??
      user.student?.institutionId ??
      user.teacher?.institutionId ??
      user.staff?.institutionId ??
      user.parent?.student?.institutionId ??
      null
    if (
      adminInstitutionId !== null &&
      userInstitutionId !== null &&
      userInstitutionId !== adminInstitutionId
    ) {
      throw new ForbiddenException('Access denied to this user')
    }

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async findByKramId(kramid: string) {
    const user = await this.prisma.user.findUnique({
      where: { kramid },
      include: {
        role: true,
        student: {
          include: {
            institution: true,
            course: true,
            parents: {
              include: {
                user: true,
              },
            },
          },
        },
        teacher: {
          include: {
            institution: true,
          },
        },
        parent: {
          include: {
            student: {
              include: {
                user: true,
                institution: true,
                course: true,
              },
            },
          },
        },
        staff: {
          include: {
            institution: true,
          },
        },
      },
    })

    if (!user) {
      throw new NotFoundException(`User with Kram ID ${kramid} not found`)
    }

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async updateByUuid(
    uuid: string,
    updateUserDto: UpdateUserDto,
    adminInstitutionId: number | null = null
  ) {
    // Check if user exists and access
    const existingUser = await this.prisma.user.findUnique({
      where: { uuid },
      include: {
        student: true,
        teacher: true,
        staff: true,
        parent: { include: { student: true } },
      },
    })

    if (!existingUser) {
      throw new NotFoundException(`User with UUID ${uuid} not found`)
    }

    const userInstitutionId =
      existingUser.institutionId ??
      existingUser.student?.institutionId ??
      existingUser.teacher?.institutionId ??
      existingUser.staff?.institutionId ??
      existingUser.parent?.student?.institutionId ??
      null
    if (
      adminInstitutionId !== null &&
      userInstitutionId !== null &&
      userInstitutionId !== adminInstitutionId
    ) {
      throw new ForbiddenException('Access denied to this user')
    }

    // Check if email already exists (if being updated)
    if (
      updateUserDto.email &&
      updateUserDto.email.toLowerCase() !== existingUser.email?.toLowerCase()
    ) {
      const emailExists = await this.prisma.user.findUnique({
        where: { email: updateUserDto.email.toLowerCase() },
      })

      if (emailExists) {
        throw new ConflictException('User with this email already exists')
      }
    }

    // Check if phone number already exists (if being updated)
    if (
      updateUserDto.phoneNumber &&
      updateUserDto.phoneNumber !== existingUser.phone
    ) {
      const phoneExists = await this.prisma.user.findFirst({
        where: { phone: updateUserDto.phoneNumber },
      })

      if (phoneExists) {
        throw new ConflictException(
          'User with this phone number already exists'
        )
      }
    }

    // Build update data with proper typing
    const updateData: Prisma.UserUpdateInput = {
      ...(updateUserDto.roleId && { roleId: updateUserDto.roleId }),
      ...(updateUserDto.email && { email: updateUserDto.email.toLowerCase() }),
      ...(updateUserDto.phoneNumber && { phone: updateUserDto.phoneNumber }),
      // Handle firstName and lastName updates
      ...(updateUserDto.firstName && { firstName: updateUserDto.firstName }),
      ...(updateUserDto.lastName && { lastName: updateUserDto.lastName }),
      // Update the combined name field for backward compatibility
      ...(updateUserDto.firstName || updateUserDto.lastName
        ? {
            name: (() => {
              const firstName =
                updateUserDto.firstName || existingUser.firstName || ''
              const lastName =
                updateUserDto.lastName || existingUser.lastName || ''
              return `${firstName} ${lastName}`.trim()
            })(),
          }
        : {}),
      ...(updateUserDto.accountStatus && {
        accountStatus: updateUserDto.accountStatus,
      }),
    }

    // Hash password if being updated
    if (updateUserDto.password) {
      updateData.passwordHash = await bcrypt.hash(updateUserDto.password, 12)
    }

    // Update user
    const user = await this.prisma.user.update({
      where: { uuid },
      data: updateData,
      include: {
        role: true,
        student: true,
        teacher: true,
        parent: true,
        staff: true,
      },
    })

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async removeByUuid(uuid: string, adminInstitutionId: number | null = null) {
    // Check if user exists and access
    const existingUser = await this.prisma.user.findUnique({
      where: { uuid },
      include: {
        student: true,
        teacher: true,
        staff: true,
        parent: { include: { student: true } },
      },
    })

    if (!existingUser) {
      throw new NotFoundException(`User with UUID ${uuid} not found`)
    }

    const userInstitutionId =
      existingUser.institutionId ??
      existingUser.student?.institutionId ??
      existingUser.teacher?.institutionId ??
      existingUser.staff?.institutionId ??
      existingUser.parent?.student?.institutionId ??
      null
    if (
      adminInstitutionId !== null &&
      userInstitutionId !== null &&
      userInstitutionId !== adminInstitutionId
    ) {
      throw new ForbiddenException('Access denied to this user')
    }

    // Soft delete by updating status
    const user = await this.prisma.user.update({
      where: { uuid },
      data: { accountStatus: 'INACTIVE' },
      include: {
        role: true,
      },
    })

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async hardDeleteByUuid(uuid: string) {
    // Check if user exists
    const existingUser = await this.prisma.user.findUnique({
      where: { uuid },
    })

    if (!existingUser) {
      throw new NotFoundException(`User with UUID ${uuid} not found`)
    }

    // Hard delete user
    await this.prisma.user.delete({
      where: { uuid },
    })

    return { message: 'User deleted successfully' }
  }

  /**
   * Create parent records for a student based on provided parent information
   */
  private async createParentRecords(
    studentId: number,
    studentData: {
      fatherInfo?: { name?: string; email?: string; mobile?: string }
      motherInfo?: { name?: string; email?: string; mobile?: string }
      guardianInfo?: { name?: string; email?: string; mobile?: string }
      guardianSameAsParent?: boolean
      guardianParentType?: 'father' | 'mother'
    },
    institutionId: number
  ) {
    const parentRole = await this.prisma.role.findFirst({
      where: { roleName: { equals: 'parent', mode: 'insensitive' } },
    })

    if (!parentRole) {
      console.warn('Parent role not found, skipping parent creation')
      return
    }

    const createdParents: Array<{
      type: string
      user: { id: number }
      parent: { id: number }
    }> = []

    // Create Father record if provided
    if (studentData.fatherInfo?.name?.trim()) {
      const fatherUser = await this.createParentUser(
        {
          name: studentData.fatherInfo.name,
          email: studentData.fatherInfo.email,
          mobile: studentData.fatherInfo.mobile,
        },
        parentRole.id,
        institutionId
      )
      if (fatherUser) {
        const fatherParent = await this.prisma.parent.create({
          data: {
            userId: fatherUser.id,
            studentId,
            relation: 'FATHER',
            isPrimaryContact: false, // Will be updated later based on guardian logic
          },
        })
        createdParents.push({
          type: 'father',
          user: fatherUser,
          parent: fatherParent,
        })
      }
    }

    // Create Mother record if provided
    if (studentData.motherInfo?.name?.trim()) {
      const motherUser = await this.createParentUser(
        {
          name: studentData.motherInfo.name,
          email: studentData.motherInfo.email,
          mobile: studentData.motherInfo.mobile,
        },
        parentRole.id,
        institutionId
      )
      if (motherUser) {
        const motherParent = await this.prisma.parent.create({
          data: {
            userId: motherUser.id,
            studentId,
            relation: 'MOTHER',
            isPrimaryContact: false, // Will be updated later based on guardian logic
          },
        })
        createdParents.push({
          type: 'mother',
          user: motherUser,
          parent: motherParent,
        })
      }
    }

    // Handle Guardian logic
    if (studentData.guardianSameAsParent && studentData.guardianParentType) {
      // Guardian is same as father or mother - mark that parent as primary contact
      const guardianParent = createdParents.find(
        p => p.type === studentData.guardianParentType
      )
      if (guardianParent) {
        await this.prisma.parent.update({
          where: { id: guardianParent.parent.id },
          data: { isPrimaryContact: true },
        })
      }
    } else if (studentData.guardianInfo?.name?.trim()) {
      // Create separate Guardian record
      const guardianUser = await this.createParentUser(
        {
          name: studentData.guardianInfo.name,
          email: studentData.guardianInfo.email,
          mobile: studentData.guardianInfo.mobile,
        },
        parentRole.id,
        institutionId
      )
      if (guardianUser) {
        await this.prisma.parent.create({
          data: {
            userId: guardianUser.id,
            studentId,
            relation: 'GUARDIAN',
            isPrimaryContact: true,
          },
        })
      }
    } else if (createdParents.length > 0) {
      // No explicit guardian, make first parent the primary contact
      await this.prisma.parent.update({
        where: { id: createdParents[0].parent.id },
        data: { isPrimaryContact: true },
      })
    }
  }

  /**
   * Create a parent user account
   */
  private async createParentUser(
    parentInfo: { name: string; email?: string; mobile?: string },
    parentRoleId: number,
    institutionId: number
  ) {
    const name = parentInfo.name.trim()
    const email = parentInfo.email?.trim()
    const mobile = parentInfo.mobile?.trim()

    // Skip if no email provided (we need email for user account)
    if (!email) {
      console.warn(`Skipping parent creation for ${name} - no email provided`)
      return null
    }

    // Check if user already exists
    const existingUser = await this.prisma.user.findUnique({
      where: { email },
    })

    if (existingUser) {
      console.log(`Parent user already exists for email: ${email}`)
      return existingUser
    }

    // Parse name into first and last name
    const [first = name, ...rest] = name.split(/\s+/)
    const lastName = rest.length > 0 ? rest.join(' ') : first

    // Generate temporary password
    const tempPassword = generateTemporaryPassword(first, lastName)
    const hashedPassword = await bcrypt.hash(tempPassword, 12)

    // Create parent user
    const parentUser = await this.prisma.user.create({
      data: {
        firstName: first,
        lastName,
        email: email?.toLowerCase(),
        phone: mobile,
        passwordHash: hashedPassword,
        roleId: parentRoleId,
        institutionId,
        accountStatus: 'INACTIVE',
      },
    })

    console.log(
      `Created parent user: ${name} (${email}) with temp password: ${tempPassword}`
    )

    // Generate Kram ID for parent user
    const kramid = await this.generateKramIdForUser(
      parentUser.id,
      institutionId,
      'parent'
    )

    return { ...parentUser, kramid }
  }

  /**
   * Generate Kram ID for a user
   */
  private async generateKramIdForUser(
    userId: number,
    institutionId: number,
    roleName: string
  ): Promise<string | null> {
    const institution = await this.prisma.institution.findUnique({
      where: { id: institutionId },
      select: { code: true },
    })

    if (!institution?.code) {
      console.warn(
        `Cannot generate Kram ID - institution code not found for ID: ${institutionId}`
      )
      return null
    }

    try {
      const result = await this.prisma.$queryRawUnsafe<{ kramid: string }[]>(
        `SELECT generate_kramid($1, $2) as kramid`,
        institution.code,
        roleName
      )

      const kramid = result[0]?.kramid ?? null
      if (kramid) {
        await this.prisma.user.update({
          where: { id: userId },
          data: { kramid },
        })
        console.log(`Generated Kram ID ${kramid} for user ${userId}`)
      }

      return kramid
    } catch (error) {
      console.error(`Failed to generate Kram ID for user ${userId}:`, error)
      return null
    }
  }
}
