import { Prisma } from '.prisma/client'
import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common'
import * as bcrypt from 'bcryptjs'
import { IdGenerationService } from '../id-generation/id-generation.service'
import { PrismaService } from '../prisma/prisma.service'
import {
  generateTemporaryPassword,
} from '../utils/kramid.util'
import { CreateUserDto, UpdateUserDto, UserQueryDto } from './dto/user.dto'

@Injectable()
export class UsersService {
  constructor(
    private prisma: PrismaService,
    private idGenerationService: IdGenerationService
  ) {}

  async create(createUserDto: CreateUserDto) {
    // Check if email already exists
    const existingUser = await this.prisma.user.findUnique({
      where: { email: createUserDto.email },
    })

    if (existingUser) {
      throw new ConflictException('User with this email already exists')
    }

    // Check if phone number already exists (if provided)
    if (createUserDto.phoneNumber) {
      const existingPhoneUser = await this.prisma.user.findFirst({
        where: { phone: createUserDto.phoneNumber },
      })

      if (existingPhoneUser) {
        throw new ConflictException(
          'User with this phone number already exists'
        )
      }
    }

    // Get role to determine what profile to create
    const role = await this.prisma.role.findUnique({
      where: { id: createUserDto.roleId },
    })

    if (!role) {
      throw new NotFoundException('Role not found')
    }

    // Get institution for Kram ID generation
    const institution = await this.prisma.institution.findUnique({
      where: { id: createUserDto.institutionId },
      select: { id: true, code: true },
    })

    if (!institution) {
      throw new NotFoundException('Institution not found')
    }

    if (!institution.code) {
      throw new BadRequestException(
        'Institution code not configured. Please contact administrator.'
      )
    }

    // Validate role-specific data is provided
    this.validateRoleSpecificData(role.roleName, createUserDto)

    // Note: Kram ID is auto-generated by database trigger
    // No need to manually generate it here

    // Generate temporary password if not provided
    const finalPassword =
      createUserDto.password ||
      generateTemporaryPassword(createUserDto.firstName, createUserDto.lastName)
    const hashedPassword = await bcrypt.hash(finalPassword, 12)
    const isTemporaryPassword = !createUserDto.password

    // Create user and role-specific profile in a transaction
    const result = await this.prisma.$transaction(async tx => {
      // Create base user
      const user = await tx.user.create({
        data: {
          roleId: createUserDto.roleId,
          email: createUserDto.email,
          passwordHash: hashedPassword,
          phone: createUserDto.phoneNumber,
          firstName: createUserDto.firstName,
          lastName: createUserDto.lastName,
          name: `${createUserDto.firstName} ${createUserDto.lastName}`,
          // kramid is auto-generated by database trigger
          emailVerified: createUserDto.isVerified || false,
          accountLocked: createUserDto.accountLocked || false,
          status: isTemporaryPassword
            ? 'INACTIVE'
            : createUserDto.status || 'ACTIVE',
          isTemporaryPassword,
          mustChangePassword: isTemporaryPassword,
        },
      })

      // Create role-specific profile
      let profile: unknown = null

      switch (role.roleName) {
        case 'student':
          if (createUserDto.studentData || role.roleName === 'student') {
            const studentData = createUserDto.studentData || {}

            // Get course code for ID generation
            let courseCode = 'GEN'
            if (studentData.courseId) {
              const course = await tx.course.findUnique({
                where: { id: studentData.courseId },
                select: { code: true },
              })
              if (course?.code) {
                courseCode = course.code
              }
            }

            // Generate IDs using IdGenerationService (outside transaction for atomic sequences)
            const admissionNumber =
              await this.idGenerationService.generateAdmissionNumber({
                institutionId: createUserDto.institutionId,
                courseCode,
                section: studentData.section,
                customValue: studentData.admissionNumber,
              })

            const rollNumber =
              await this.idGenerationService.generateRollNumber({
                institutionId: createUserDto.institutionId,
                courseCode,
                section: studentData.section,
                customValue: studentData.rollNumber,
              })

            profile = await tx.student.create({
              data: {
                userId: user.id,
                institutionId: createUserDto.institutionId,
                courseId: studentData.courseId,
                admissionNumber,
                rollNumber,
                admissionDate: studentData.admissionDate
                  ? new Date(studentData.admissionDate)
                  : null,
                currentSemester: studentData.currentSemester,
                currentYear: studentData.currentYear,
                gradeLevel: studentData.gradeLevel,
                section: studentData.section,
                studentType: studentData.studentType || 'REGULAR',
                residentialStatus:
                  studentData.residentialStatus || 'DAY_SCHOLAR',
                transportRequired: studentData.transportRequired || false,
                emergencyContactName: studentData.emergencyContactName,
                emergencyContactPhone: studentData.emergencyContactPhone,
                emergencyContactEmail: studentData.emergencyContactEmail,
                bloodGroup: studentData.bloodGroup,
                medicalConditions: studentData.medicalConditions,
              },
            })
          }
          break

        case 'teacher':
          if (createUserDto.teacherData || role.roleName === 'teacher') {
            const teacherData = createUserDto.teacherData || {}

            // Generate employee ID using IdGenerationService
            const employeeId =
              await this.idGenerationService.generateTeacherEmployeeId({
                institutionId: createUserDto.institutionId,
                customValue: teacherData.employeeId,
              })

            profile = await tx.teacher.create({
              data: {
                userId: user.id,
                institutionId: createUserDto.institutionId,
                employeeId,
                designation: teacherData.designation,
                specialization: teacherData.specialization,
                qualification: teacherData.qualification,
                experienceYears: teacherData.experienceYears,
                joinDate: teacherData.joinDate
                  ? new Date(teacherData.joinDate)
                  : null,
                salary: teacherData.salary,
                employmentType: teacherData.employmentType || 'FULL_TIME',
                officeLocation: teacherData.officeLocation,
                officeHours: teacherData.officeHours,
                researchInterests: teacherData.researchInterests,
                publications: teacherData.publications,
              },
            })
          }
          break

        case 'staff':
          if (createUserDto.staffData) {
            const staffData = createUserDto.staffData

            // Generate employee ID using IdGenerationService
            const employeeId =
              await this.idGenerationService.generateStaffEmployeeId({
                institutionId: createUserDto.institutionId,
                customValue: staffData.employeeId,
              })

            profile = await tx.staff.create({
              data: {
                userId: user.id,
                institutionId: createUserDto.institutionId,
                employeeId,
                staffType: staffData.staffType,
                designation: staffData.designation,
                department: staffData.department,
                joinDate: staffData.joinDate
                  ? new Date(staffData.joinDate)
                  : null,
                salary: staffData.salary,
                employmentType: staffData.employmentType || 'FULL_TIME',
                workingHours: staffData.workingHours,
                qualifications: staffData.qualifications,
                experience: staffData.experience,
                emergencyContact: staffData.emergencyContact,
                address: staffData.address,
              },
            })
          }
          break

        case 'parent':
          if (createUserDto.parentData?.childKramid) {
            // Find the child student by Kram ID
            const childUser = await tx.user.findUnique({
              where: { kramid: createUserDto.parentData.childKramid },
              include: { student: true },
            })

            if (!childUser || !childUser.student) {
              throw new NotFoundException(
                'Student not found with the provided Kram ID'
              )
            }

            profile = await tx.parent.create({
              data: {
                userId: user.id,
                studentId: childUser.student.id,
                relation:
                  (createUserDto.parentData.relation as
                    | 'FATHER'
                    | 'MOTHER'
                    | 'GUARDIAN'
                    | 'OTHER') || 'GUARDIAN',
                isPrimaryContact:
                  createUserDto.parentData.isPrimaryContact ?? true,
                occupation: createUserDto.parentData.occupation,
                annualIncome: createUserDto.parentData.annualIncome,
                educationLevel: createUserDto.parentData.educationLevel,
              },
            })
          } else {
            throw new BadRequestException(
              'parentData with childKramid is required for parent role'
            )
          }
          break

        // Admin and super_admin don't need additional profiles
        case 'admin':
        case 'super_admin':
          // No additional profile needed
          break

        default:
          // For any other roles, no additional profile
          break
      }

      return {
        user,
        profile,
        generatedPassword: isTemporaryPassword ? finalPassword : null,
      }
    })

    // Fetch complete user with all relations
    const completeUser = await this.prisma.user.findUnique({
      where: { id: result.user.id },
      include: {
        role: true,
        student: {
          include: {
            institution: { select: { id: true, name: true, type: true } },
            course: { select: { id: true, name: true, code: true } },
          },
        },
        teacher: {
          include: {
            institution: { select: { id: true, name: true, type: true } },
          },
        },
        parent: {
          include: {
            student: {
              include: {
                user: {
                  select: {
                    id: true,
                    name: true,
                    email: true,
                    kramid: true,
                  },
                },
              },
            },
          },
        },
        staff: {
          include: {
            institution: { select: { id: true, name: true, type: true } },
          },
        },
      },
    })

    // Remove passwordHash from response
    if (completeUser) {
      delete completeUser.passwordHash
    }

    return {
      success: true,
      message: 'User created successfully',
      data: completeUser,
      ...(result.generatedPassword && {
        temporaryPassword: result.generatedPassword,
        note: 'User must change password on first login',
      }),
    }
  }

  private validateRoleSpecificData(
    roleName: string,
    createUserDto: CreateUserDto
  ) {
    switch (roleName) {
      case 'student':
        // studentData is optional - admissionNumber/rollNumber auto-generated
        break

      case 'teacher':
        // teacherData is optional - employeeId auto-generated
        break

      case 'staff':
        if (
          !createUserDto.staffData?.staffType ||
          !createUserDto.staffData?.designation
        ) {
          throw new BadRequestException(
            'staffData with staffType and designation is required for staff role'
          )
        }
        break

      case 'parent':
        if (!createUserDto.parentData?.childKramid) {
          throw new BadRequestException(
            'parentData with childKramid is required for parent role'
          )
        }
        break

      // admin, super_admin don't require additional data
    }
  }

  async findAll(query: UserQueryDto, institutionId: number | null = null) {
    const { page, limit, search, roleId, status, sortBy, sortOrder } = query
    const skip = (page - 1) * limit

    // Build where clause with proper Prisma typing
    const where: Prisma.UserWhereInput = {
      ...(search && {
        OR: [
          { name: { contains: search, mode: 'insensitive' } },
          { firstName: { contains: search, mode: 'insensitive' } },
          { lastName: { contains: search, mode: 'insensitive' } },
          { email: { contains: search, mode: 'insensitive' } },
          { phone: { contains: search, mode: 'insensitive' } },
        ],
      }),
      ...(roleId && { roleId }),
      ...(status && { status }),
    }

    if (institutionId) {
      where.AND = [
        ...(Array.isArray(where.AND) ? where.AND : []),
        {
          OR: [
            { institutionId },
            { student: { institutionId } },
            { teacher: { institutionId } },
            { staff: { institutionId } },
            { parent: { student: { institutionId } } },
          ],
        },
      ]
    }

    // Build orderBy clause with proper typing
    const orderBy: Prisma.UserOrderByWithRelationInput = {
      [sortBy]: sortOrder,
    }

    // Get users with pagination
    const [users, total] = await Promise.all([
      this.prisma.user.findMany({
        where,
        skip,
        take: limit,
        orderBy,
        include: {
          role: true,
          student: true,
          teacher: true,
          parent: true,
          staff: true,
        },
      }),
      this.prisma.user.count({ where }),
    ])

    // Remove passwordHash from response
    const usersWithoutPasswords = users.map(user => {
      delete user.passwordHash
      return user
    })

    return {
      data: usersWithoutPasswords,
      pagination: {
        page,
        limit,
        total,
        pages: Math.ceil(total / limit),
      },
    }
  }

  async findOne(id: number) {
    const user = await this.prisma.user.findUnique({
      where: { id },
      include: {
        role: true,
        student: {
          include: {
            institution: true,
            course: true,
            parents: {
              include: {
                user: true,
              },
            },
          },
        },
        teacher: {
          include: {
            institution: true,
          },
        },
        parent: {
          include: {
            student: {
              include: {
                user: true,
                institution: true,
                course: true,
              },
            },
          },
        },
        staff: {
          include: {
            institution: true,
          },
        },
      },
    })

    if (!user) {
      throw new NotFoundException(`User with ID ${id} not found`)
    }

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async findByEmail(email: string) {
    const user = await this.prisma.user.findUnique({
      where: { email },
      include: {
        role: true,
        student: true,
        teacher: true,
        parent: true,
        staff: true,
      },
    })

    if (!user) {
      throw new NotFoundException(`User with email ${email} not found`)
    }

    return user
  }

  async update(id: number, updateUserDto: UpdateUserDto) {
    // Check if user exists
    const existingUser = await this.prisma.user.findUnique({
      where: { id },
    })

    if (!existingUser) {
      throw new NotFoundException(`User with ID ${id} not found`)
    }

    // Check if email already exists (if being updated)
    if (updateUserDto.email && updateUserDto.email !== existingUser.email) {
      const emailExists = await this.prisma.user.findUnique({
        where: { email: updateUserDto.email },
      })

      if (emailExists) {
        throw new ConflictException('User with this email already exists')
      }
    }

    // Check if phone number already exists (if being updated)
    if (
      updateUserDto.phoneNumber &&
      updateUserDto.phoneNumber !== existingUser.phone
    ) {
      const phoneExists = await this.prisma.user.findFirst({
        where: { phone: updateUserDto.phoneNumber },
      })

      if (phoneExists) {
        throw new ConflictException(
          'User with this phone number already exists'
        )
      }
    }

    // Build update data with proper typing
    const updateData: Prisma.UserUpdateInput = {
      ...(updateUserDto.roleId && { roleId: updateUserDto.roleId }),
      ...(updateUserDto.email && { email: updateUserDto.email }),
      ...(updateUserDto.phoneNumber && { phone: updateUserDto.phoneNumber }),
      // Handle firstName and lastName updates
      ...(updateUserDto.firstName && { firstName: updateUserDto.firstName }),
      ...(updateUserDto.lastName && { lastName: updateUserDto.lastName }),
      // Update the combined name field for backward compatibility
      ...(updateUserDto.firstName || updateUserDto.lastName
        ? {
            name: (() => {
              const firstName =
                updateUserDto.firstName || existingUser.firstName || ''
              const lastName =
                updateUserDto.lastName || existingUser.lastName || ''
              return `${firstName} ${lastName}`.trim()
            })(),
          }
        : {}),
      ...(updateUserDto.isVerified !== undefined && {
        emailVerified: updateUserDto.isVerified,
      }),
      ...(updateUserDto.accountLocked !== undefined && {
        accountLocked: updateUserDto.accountLocked,
      }),
      ...(updateUserDto.status && { status: updateUserDto.status }),
    }

    // Hash password if being updated
    if (updateUserDto.password) {
      updateData.passwordHash = await bcrypt.hash(updateUserDto.password, 12)
    }

    // Update user
    const user = await this.prisma.user.update({
      where: { id },
      data: updateData,
      include: {
        role: true,
        student: true,
        teacher: true,
        parent: true,
        staff: true,
      },
    })

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async remove(id: number) {
    // Check if user exists
    const existingUser = await this.prisma.user.findUnique({
      where: { id },
    })

    if (!existingUser) {
      throw new NotFoundException(`User with ID ${id} not found`)
    }

    // Soft delete by updating status
    const user = await this.prisma.user.update({
      where: { id },
      data: { status: 'INACTIVE' },
      include: {
        role: true,
      },
    })

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async hardDelete(id: number) {
    // Check if user exists
    const existingUser = await this.prisma.user.findUnique({
      where: { id },
    })

    if (!existingUser) {
      throw new NotFoundException(`User with ID ${id} not found`)
    }

    // Hard delete user
    await this.prisma.user.delete({
      where: { id },
    })

    return { message: 'User deleted successfully' }
  }

  async getUsersByRole(
    roleId: number,
    query: UserQueryDto,
    institutionId: number | null = null
  ) {
    const { page, limit, search, status, sortBy, sortOrder } = query
    const skip = (page - 1) * limit

    // Build where clause with proper Prisma typing
    const where: Prisma.UserWhereInput = {
      roleId,
      ...(search && {
        OR: [
          { name: { contains: search, mode: 'insensitive' } },
          { email: { contains: search, mode: 'insensitive' } },
          { phone: { contains: search, mode: 'insensitive' } },
        ],
      }),
      ...(status && { status }),
    }

    if (institutionId) {
      where.AND = [
        ...(Array.isArray(where.AND) ? where.AND : []),
        {
          OR: [
            { institutionId },
            { student: { institutionId } },
            { teacher: { institutionId } },
            { staff: { institutionId } },
            { parent: { student: { institutionId } } },
          ],
        },
      ]
    }

    // Build orderBy clause with proper typing
    const orderBy: Prisma.UserOrderByWithRelationInput = {
      [sortBy]: sortOrder,
    }

    // Get users with pagination
    const [users, total] = await Promise.all([
      this.prisma.user.findMany({
        where,
        skip,
        take: limit,
        orderBy,
        include: {
          role: true,
          student: true,
          teacher: true,
          parent: true,
          staff: true,
        },
      }),
      this.prisma.user.count({ where }),
    ])

    // Remove passwordHash from response
    const usersWithoutPasswords = users.map(user => {
      delete user.passwordHash
      return user
    })

    return {
      data: usersWithoutPasswords,
      pagination: {
        page,
        limit,
        total,
        pages: Math.ceil(total / limit),
      },
    }
  }

  async getUsersStats(institutionId: number | null = null) {
    const instWhere: Prisma.UserWhereInput | undefined = institutionId
      ? {
          OR: [
            { institutionId },
            { student: { institutionId } },
            { teacher: { institutionId } },
            { staff: { institutionId } },
            { parent: { student: { institutionId } } },
          ],
        }
      : undefined

    const baseWhere = instWhere ?? {}
    const [totalUsers, activeUsers, inactiveUsers, usersByRole] =
      await Promise.all([
        this.prisma.user.count({ where: baseWhere }),
        this.prisma.user.count({
          where: { ...baseWhere, status: 'ACTIVE' },
        }),
        this.prisma.user.count({
          where: { ...baseWhere, status: 'INACTIVE' },
        }),
        this.prisma.user.groupBy({
          by: ['roleId'],
          _count: { id: true },
          ...(instWhere && { where: instWhere }),
        }),
      ])

    // Get role names separately
    const roleIds = usersByRole.map(item => item.roleId)
    const roles = await this.prisma.role.findMany({
      where: { id: { in: roleIds } },
      select: { id: true, roleName: true },
    })

    const roleMap = new Map(roles.map(role => [role.id, role.roleName]))

    return {
      totalUsers,
      activeUsers,
      inactiveUsers,
      suspendedUsers: totalUsers - activeUsers - inactiveUsers,
      usersByRole: usersByRole.map(({ roleId, _count }) => ({
        roleId,
        count: _count.id,
        roleName: roleMap.get(roleId) || 'Unknown',
      })),
    }
  }

  // UUID-based methods
  async findByUuid(uuid: string, adminInstitutionId: number | null = null) {
    const user = await this.prisma.user.findUnique({
      where: { uuid },
      include: {
        role: true,
        student: {
          include: {
            institution: true,
            course: true,
            parents: {
              include: {
                user: true,
              },
            },
          },
        },
        teacher: {
          include: {
            institution: true,
          },
        },
        parent: {
          include: {
            student: {
              include: {
                user: true,
                institution: true,
                course: true,
              },
            },
          },
        },
        staff: {
          include: {
            institution: true,
          },
        },
      },
    })

    if (!user) {
      throw new NotFoundException(`User with UUID ${uuid} not found`)
    }

    const userInstitutionId =
      user.institutionId ??
      user.student?.institutionId ??
      user.teacher?.institutionId ??
      user.staff?.institutionId ??
      user.parent?.student?.institutionId ??
      null
    if (
      adminInstitutionId !== null &&
      userInstitutionId !== null &&
      userInstitutionId !== adminInstitutionId
    ) {
      throw new ForbiddenException('Access denied to this user')
    }

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async findByKramId(kramid: string) {
    const user = await this.prisma.user.findUnique({
      where: { kramid },
      include: {
        role: true,
        student: {
          include: {
            institution: true,
            course: true,
            parents: {
              include: {
                user: true,
              },
            },
          },
        },
        teacher: {
          include: {
            institution: true,
          },
        },
        parent: {
          include: {
            student: {
              include: {
                user: true,
                institution: true,
                course: true,
              },
            },
          },
        },
        staff: {
          include: {
            institution: true,
          },
        },
      },
    })

    if (!user) {
      throw new NotFoundException(`User with Kram ID ${kramid} not found`)
    }

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async updateByUuid(
    uuid: string,
    updateUserDto: UpdateUserDto,
    adminInstitutionId: number | null = null
  ) {
    // Check if user exists and access
    const existingUser = await this.prisma.user.findUnique({
      where: { uuid },
      include: {
        student: true,
        teacher: true,
        staff: true,
        parent: { include: { student: true } },
      },
    })

    if (!existingUser) {
      throw new NotFoundException(`User with UUID ${uuid} not found`)
    }

    const userInstitutionId =
      existingUser.institutionId ??
      existingUser.student?.institutionId ??
      existingUser.teacher?.institutionId ??
      existingUser.staff?.institutionId ??
      existingUser.parent?.student?.institutionId ??
      null
    if (
      adminInstitutionId !== null &&
      userInstitutionId !== null &&
      userInstitutionId !== adminInstitutionId
    ) {
      throw new ForbiddenException('Access denied to this user')
    }

    // Check if email already exists (if being updated)
    if (updateUserDto.email && updateUserDto.email !== existingUser.email) {
      const emailExists = await this.prisma.user.findUnique({
        where: { email: updateUserDto.email },
      })

      if (emailExists) {
        throw new ConflictException('User with this email already exists')
      }
    }

    // Check if phone number already exists (if being updated)
    if (
      updateUserDto.phoneNumber &&
      updateUserDto.phoneNumber !== existingUser.phone
    ) {
      const phoneExists = await this.prisma.user.findFirst({
        where: { phone: updateUserDto.phoneNumber },
      })

      if (phoneExists) {
        throw new ConflictException(
          'User with this phone number already exists'
        )
      }
    }

    // Build update data with proper typing
    const updateData: Prisma.UserUpdateInput = {
      ...(updateUserDto.roleId && { roleId: updateUserDto.roleId }),
      ...(updateUserDto.email && { email: updateUserDto.email }),
      ...(updateUserDto.phoneNumber && { phone: updateUserDto.phoneNumber }),
      // Handle firstName and lastName updates
      ...(updateUserDto.firstName && { firstName: updateUserDto.firstName }),
      ...(updateUserDto.lastName && { lastName: updateUserDto.lastName }),
      // Update the combined name field for backward compatibility
      ...(updateUserDto.firstName || updateUserDto.lastName
        ? {
            name: (() => {
              const firstName =
                updateUserDto.firstName || existingUser.firstName || ''
              const lastName =
                updateUserDto.lastName || existingUser.lastName || ''
              return `${firstName} ${lastName}`.trim()
            })(),
          }
        : {}),
      ...(updateUserDto.isVerified !== undefined && {
        emailVerified: updateUserDto.isVerified,
      }),
      ...(updateUserDto.accountLocked !== undefined && {
        accountLocked: updateUserDto.accountLocked,
      }),
      ...(updateUserDto.status && { status: updateUserDto.status }),
    }

    // Hash password if being updated
    if (updateUserDto.password) {
      updateData.passwordHash = await bcrypt.hash(updateUserDto.password, 12)
    }

    // Update user
    const user = await this.prisma.user.update({
      where: { uuid },
      data: updateData,
      include: {
        role: true,
        student: true,
        teacher: true,
        parent: true,
        staff: true,
      },
    })

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async removeByUuid(uuid: string, adminInstitutionId: number | null = null) {
    // Check if user exists and access
    const existingUser = await this.prisma.user.findUnique({
      where: { uuid },
      include: {
        student: true,
        teacher: true,
        staff: true,
        parent: { include: { student: true } },
      },
    })

    if (!existingUser) {
      throw new NotFoundException(`User with UUID ${uuid} not found`)
    }

    const userInstitutionId =
      existingUser.institutionId ??
      existingUser.student?.institutionId ??
      existingUser.teacher?.institutionId ??
      existingUser.staff?.institutionId ??
      existingUser.parent?.student?.institutionId ??
      null
    if (
      adminInstitutionId !== null &&
      userInstitutionId !== null &&
      userInstitutionId !== adminInstitutionId
    ) {
      throw new ForbiddenException('Access denied to this user')
    }

    // Soft delete by updating status
    const user = await this.prisma.user.update({
      where: { uuid },
      data: { status: 'INACTIVE' },
      include: {
        role: true,
      },
    })

    // Remove passwordHash from response
    delete user.passwordHash
    return user
  }

  async hardDeleteByUuid(uuid: string) {
    // Check if user exists
    const existingUser = await this.prisma.user.findUnique({
      where: { uuid },
    })

    if (!existingUser) {
      throw new NotFoundException(`User with UUID ${uuid} not found`)
    }

    // Hard delete user
    await this.prisma.user.delete({
      where: { uuid },
    })

    return { message: 'User deleted successfully' }
  }
}
