/**
 * Kram ID Generation Utility
 *
 * Generates unique Kram IDs for users based on their institution and role
 * Format: {INST_CODE}-{ROLE}{YY}-{RAND4}
 *
 * Examples:
 * - DPS-S25-K8M2 (Student at Delhi Public School, 2025)
 * - IITD-T25-P9X7 (Teacher at IIT Delhi, 2025)
 * - SSC-AD25-L3N8 (Admin at St. Stephen's College, 2025)
 * - MU-P25-Q4R6 (Parent at Manipal University, 2025)
 */

/**
 * Role code mapping
 */
const ROLE_CODES: Record<string, string> = {
  super_admin: 'SA',
  admin: 'AD',
  teacher: 'T',
  student: 'S',
  parent: 'P',
  staff: 'SF',
}

/**
 * Generate institution code from institution name
 * Creates a 2-4 character acronym based on significant words
 *
 * @param institutionName - The full name of the institution
 * @param existingCodes - Optional array of existing codes to avoid duplicates
 * @returns Institution code (2-4 characters)
 *
 * @example
 * generateInstitutionCode("Delhi Public School") // "DPS"
 * generateInstitutionCode("Indian Institute of Technology Delhi") // "IITD"
 * generateInstitutionCode("Delhi University") // "DU"
 * generateInstitutionCode("St. Stephen's College") // "SSC"
 */
export function generateInstitutionCode(
  institutionName: string,
  existingCodes: string[] = []
): string {
  // Clean and normalize the name
  const cleanName = institutionName.trim()

  // Common words to ignore when creating acronym
  const skipWords = [
    'the',
    'of',
    'and',
    '&',
    'a',
    'an',
    'for',
    'in',
    'at',
    'to',
  ]

  // Split into words and filter out common words and short words
  const words = cleanName
    .toLowerCase()
    .split(/[\s\-,.()]+/)
    .filter(word => word.length > 0 && !skipWords.includes(word))

  // Strategy 1: Create acronym from first letters of significant words (max 4)
  let code = words
    .slice(0, 4)
    .map(word => word[0].toUpperCase())
    .join('')

  // Strategy 2: If acronym is too short, use first N characters from name
  if (code.length < 2) {
    code = cleanName
      .replace(/[^a-zA-Z0-9]/g, '')
      .slice(0, 3)
      .toUpperCase()
  }

  // Limit to 2-4 characters
  code = code.slice(0, 4)

  // Ensure minimum 2 characters
  if (code.length < 2) {
    code = code.padEnd(2, 'X')
  }

  // Handle duplicates by adding numeric suffix
  let finalCode = code
  let suffix = 1
  while (existingCodes.includes(finalCode)) {
    // If adding suffix would exceed 4 chars, truncate the base code
    const baseCode = code.length >= 4 ? code.slice(0, 3) : code
    finalCode = baseCode + suffix
    suffix++
  }

  return finalCode
}

/**
 * Validate institution code format
 * @param code - The institution code to validate
 * @returns true if valid (2-4 alphanumeric characters), false otherwise
 */
export function isValidInstitutionCode(code: string): boolean {
  return /^[A-Z0-9]{2,4}$/.test(code)
}

/**
 * Generate random alphanumeric code (excludes ambiguous characters)
 * Excludes: 0, O, 1, I to avoid confusion
 *
 * @param length - Length of the random code
 * @returns Random code string
 */
function generateRandomCode(length: number): string {
  const chars = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ'
  let result = ''
  const crypto = require('crypto')

  for (let i = 0; i < length; i++) {
    const randomIndex = crypto.randomInt(0, chars.length)
    result += chars.charAt(randomIndex)
  }

  return result
}

/**
 * Generate Kram ID with institution code
 * NOTE: In production, Kram IDs are auto-generated by the database.
 * This function is kept for backwards compatibility and testing purposes.
 *
 * @param institutionCode - The institution code (2-4 characters)
 * @param roleName - The role name (e.g., 'student', 'teacher')
 * @param year - Optional year (defaults to current year)
 * @returns Kram ID string
 *
 * @example
 * generateKramId("DPS", "student") // "DPS-S25-K8M2"
 * generateKramId("IITD", "teacher", 2024) // "IITD-T24-P9X7"
 */
export function generateKramId(
  institutionCode: string,
  roleName: string,
  year?: number
): string {
  const roleCode = ROLE_CODES[roleName.toLowerCase()] || 'U' // 'U' for Unknown
  const currentYear = year || new Date().getFullYear()
  const yearShort = currentYear.toString().slice(-2) // Last 2 digits
  const randomCode = generateRandomCode(4)

  // Normalize institution code to uppercase
  const instCode = institutionCode.toUpperCase()

  return `${instCode}-${roleCode}${yearShort}-${randomCode}`
}

/**
 * Parse Kram ID to extract components
 *
 * @param kramid - The Kram ID to parse
 * @returns Object containing institution code, role code, year, and random code
 *
 * @example
 * parseKramId("DPS-S25-K8M2")
 * // Returns: { institutionCode: "DPS", roleCode: "S", year: 2025, randomCode: "K8M2" }
 */
export function parseKramId(kramid: string): {
  institutionCode: string
  roleCode: string
  year: number
  randomCode: string
} | null {
  // Pattern: {2-4 chars}-{1-2 chars}{2 digits}-{4 chars}
  const pattern = /^([A-Z0-9]{2,4})-([A-Z]{1,2})(\d{2})-([A-Z0-9]{4})$/
  const match = kramid.match(pattern)

  if (!match) {
    return null
  }

  return {
    institutionCode: match[1],
    roleCode: match[2],
    year: 2000 + parseInt(match[3], 10), // Convert 25 -> 2025
    randomCode: match[4],
  }
}

/**
 * Validate Kram ID format
 *
 * @param kramid - The Kram ID to validate
 * @returns true if valid, false otherwise
 *
 * @example
 * isValidKramId("DPS-S25-K8M2") // true
 * isValidKramId("INVALID-ID") // false
 */
export function isValidKramId(kramid: string): boolean {
  return /^[A-Z0-9]{2,4}-[A-Z]{1,2}\d{2}-[A-Z0-9]{4}$/.test(kramid)
}

/**
 * Get role name from Kram ID
 *
 * @param kramid - The Kram ID
 * @returns Role name or null if invalid
 *
 * @example
 * getRoleNameFromKramId("DPS-S25-K8M2") // "student"
 * getRoleNameFromKramId("IITD-T25-P9X7") // "teacher"
 */
export function getRoleNameFromKramId(kramid: string): string | null {
  const parsed = parseKramId(kramid)
  if (!parsed) return null

  const roleEntry = Object.entries(ROLE_CODES).find(
    ([_, code]) => code === parsed.roleCode
  )

  return roleEntry ? roleEntry[0] : null
}

/**
 * Get institution code from Kram ID
 *
 * @param kramid - The Kram ID
 * @returns Institution code or null if invalid
 *
 * @example
 * getInstitutionCodeFromKramId("DPS-S25-K8M2") // "DPS"
 */
export function getInstitutionCodeFromKramId(
  kramid: string
): string | null {
  const parsed = parseKramId(kramid)
  return parsed ? parsed.institutionCode : null
}

/**
 * Generate temporary password based on user's name and current year
 * Format: First 4 letters of name (uppercase) + current year
 * Example: "Namit Thakral" -> "NAMI2026"
 *
 * @param firstName - User's first name
 * @param lastName - User's last name (optional)
 * @returns Temporary password string
 */
export function generateTemporaryPassword(
  firstName: string,
  lastName?: string
): string {
  const year = new Date().getFullYear()

  // Combine first and last name, remove non-alphabetic characters
  const fullName = `${firstName}${lastName || ''}`.replace(/[^a-zA-Z]/g, '')

  // Get first 4 characters (or less if name is shorter)
  const namePrefix = fullName.substring(0, 4).toUpperCase()

  // Pad with 'X' if name is too short
  const paddedPrefix = namePrefix.padEnd(4, 'X')

  return `${paddedPrefix}${year}`
}

/**
 * Generate Admission Number for a student
 * Format: {YEAR}/{COURSE_CODE}/{SEQUENCE}
 * Example: "2025/CS/00042"
 *
 * @param year - Admission year
 * @param courseCode - Course code (e.g., "CS", "ECE")
 * @param sequence - Sequence number (will be padded to 5 digits)
 * @returns Admission number string
 */
export function generateAdmissionNumber(
  year: number,
  courseCode: string,
  sequence: number
): string {
  const paddedSequence = sequence.toString().padStart(5, '0')
  return `${year}/${courseCode.toUpperCase()}/${paddedSequence}`
}

/**
 * Generate Roll Number for a student
 * Format: {COURSE_CODE}-{SECTION}-{SEQUENCE}
 * Example: "CS-A-001"
 *
 * @param courseCode - Course code (e.g., "CS", "ECE")
 * @param section - Section (e.g., "A", "B")
 * @param sequence - Sequence number (will be padded to 3 digits)
 * @returns Roll number string
 */
export function generateRollNumber(
  courseCode: string,
  section: string,
  sequence: number
): string {
  const paddedSequence = sequence.toString().padStart(3, '0')
  return `${courseCode.toUpperCase()}-${section.toUpperCase()}-${paddedSequence}`
}

/**
 * Generate Employee ID for a teacher or staff member
 * Format: {PREFIX}-{YEAR}-{SEQUENCE}
 * Example: "EMP-2025-00015" for teacher, "STF-2025-00008" for staff
 *
 * @param type - 'teacher' or 'staff'
 * @param year - Year of joining
 * @param sequence - Sequence number (will be padded to 5 digits)
 * @returns Employee ID string
 */
export function generateEmployeeId(
  type: 'teacher' | 'staff',
  year: number,
  sequence: number
): string {
  const prefix = type === 'teacher' ? 'EMP' : 'STF'
  const paddedSequence = sequence.toString().padStart(5, '0')
  return `${prefix}-${year}-${paddedSequence}`
}
